fix #34 NoClassDefFoundError: javax/xml/bind/JAXBException at runtime
ChangeVision/astah-cpp-reverse-plugin pull request #35
Opened 2024-12-02 00:49 UTC by astah-harry

fix #34

2024-12-02 05:39 UTC, myamamoto requested changes
@astah-harry 
- 全般的にフォーマットしてください。（タブはスペースに）
- バージョンアップしたjarはNexusにアップロードが必要です
  - 各jarのバージョンは以下のようにしてください
    - astah-api-util 1.1.0
    - astah-reverse-jaxb-doxygen 1.10
    - astah-cpp-reverse-plugin 1.2.0
- astah10.0以降で有効にする必要ない？
- logbackの更新ブランチも取り込んでjarを作って動作確認したい

2024-12-02 07:37 UTC, astah-harry commented
@myamamoto
>変更箇所をフォーマットしてください。（タブはスペースに）

対応した

>バージョンアップしたjarはNexusにアップロードが必要です

バージョン修正しました、uploadは明日山本さんお願いします

>logbackの更新ブランチもこのバージョンに取り込んで動作確認したい

更新した

>astah10.0以降から有効とする必要があるのではないか
現状、9.2ではエラーになり読み込めないので、原因を明らかにする

原因はよくわからないですけど、
9.2はjava8で、プラグインは色々依存はjava21に上げたら、pro9.2で無効するのは可能性高くて、合理ですね。

2024-12-02 22:01 UTC, myamamoto commented
@astah-harry 

> > astah10.0以降から有効とする必要があるのではないか
> > 現状、9.2ではエラーになり読み込めないので、原因を明らかにする
> 
> 原因はよくわからないですけど、 9.2はjava8で、プラグインは色々依存はjava21に上げたら、pro9.2で無効するのは可能性高くて、合理ですね。

それならastah.versionを10.0にしてください
また、astah-reverse-jaxb-doxygenが依存するastah-api-utilのバージョンが変更されていません

2024-12-03 00:13 UTC, astah-harry commented
>それならastah.versionを10.0にしてください
また、astah-reverse-jaxb-doxygenが依存するastah-api-utilのバージョンが変更されていません

はい、変更しました。
本PRの頭に添付したinstallerも更新しました、また確認してください。

2024-12-03 00:14 UTC, astah-harry commented
>それならastah.versionを10.0にしてください
また、astah-reverse-jaxb-doxygenが依存するastah-api-utilのバージョンが変更されていません

@myamamoto はい、変更しました。
本PRの頭に添付したinstallerも更新しました、また確認してください。

2024-12-03 04:16 UTC, myamamoto approved these changes

2024-12-03 04:16 UTC, merged